### PR TITLE
Add package hashes to requirements

### PR DESCRIPTION
**Pull request by kristapsk**
Adds extra protection layer in case pypi.org gets compromised. And it's really simple to do, just `pip install hashin` and then, when changing `requirements.txt`, just run `hashin package` (for example, `hashin python-bitcoinrpc==1.0`), it will update `requirements.txt` with hash(es).

### CODE REVIEW

**Comment by surfer190** [comment]
I am getting this with `pip install -r requirements.txt`.
Using `Python 3.9.9`.

```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    Jinja2<3.0,>=2.10.1 from https://files.pythonhosted.org/packages/7e/c2/1eece8c95ddbc9b1aeb64f5783a9e07a286de42191b7204d67b7496ddf35/Jinja2-2.11.3-py2.py3-none-any.whl#sha256=03e47ad063331dd6a3f04a43eddca8a966a26ba0c5b7207a9a9e4e08f1b29419 (from Flask==1.1.4->-r requirements.txt (line 5))
```

**Comment by kristapsk** [comment]
@surfer190 That commit is reverted for now, until I fix it, so now you should be able to install with current master.

**Comment by surfer190** [comment]
Thanks @kristapsk. The reason for the hashing of packages - is that to prevent a supply chain pypi threat? Do you know a resource to read up on how pip does package hashes in requirements?

**Comment by kristapsk** [comment]
> Thanks @kristapsk. The reason for the hashing of packages - is that to prevent a supply chain pypi threat?

Yes, that's the idea. PyPi kinda doesn't allow overwriting files, but if they got compromised, such things could happen. But then you also need pined versions with hashes for dependencies too (which kinda isn't bad idea), so that raises problems (it's solvable, just I got problems with some packages with version range and newer ones had problems with GCC 11, etc, just don't have to solve that right now).

> Do you know a resource to read up on how pip does package hashes in requirements?

Not sure, but good idea to look how that process happens. But, in any case, even if it's not completely transparent, sounds for me better than nothing.

**Comment by kristapsk** [comment]
> but if they got compromised, such things could happen.

I know this sounds paranoic, but in Bitcoin we should always go in paranoia to the max IMO. :)

**Pull request merged**
