### PR TITLE
Fix missing import logging

### PR DESCRIPTION
**Pull request by steepdawn974**
Fixes error `NameError: name 'logging' is not defined` when using tor.py

### CODE REVIEW

**Comment by nickfarrow** [comment]
ill cherry pick this commit soon, or feel free to try rebase

**Comment by steepdawn974** [comment]
> ill cherry pick this commit soon, or feel free to try rebase

Yes please. you only need commit abe7969ebdefd1f92343f6aa84768ea03d313ea1
If not, then just close/delete this PR. There is literally just one change; `import logging` in `tor.py`  - you can add this manually without my PR.


I had attempted to cleanup some items from my git log, I ran carelessly ran a script that crawled through my git history and fixed & reapplied commits. It has now messed up my repo, and even `git reset --hard upstream master` or a rebase can't seem to salvage this PR. It always tries to merge these other old 237 commits  :-/

If I cant get this sorted, I will delete my repo, and make a new fork.

**Comment by steepdawn974** [comment]
@nickfarrow I managed to resolve all the conflics and rebase after all. Should be ready to merge

**Comment by nickfarrow** [comment]
merged https://github.com/SatSale/SatSale/commit/09f1f0c330a7a1b3036821fbfaf49e23f9184b66

**Pull request closed without merging**
